# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_slab_swig', [dirname(__file__)])
        except ImportError:
            import _slab_swig
            return _slab_swig
        if fp is not None:
            try:
                _mod = imp.load_module('_slab_swig', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _slab_swig = swig_import_helper()
    del swig_import_helper
else:
    import _slab_swig
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


def _swig_setattr_nondynamic_method(set):
    def set_attr(self,name,value):
        if (name == "thisown"): return self.this.own(value)
        if hasattr(self,name) or (name == "this"):
            set(self,name,value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


class SwigPyIterator(object):
    """Proxy of C++ swig::SwigPyIterator class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _slab_swig.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self):
        """value(self) -> PyObject"""
        return _slab_swig.SwigPyIterator_value(self)

    def incr(self, n = 1):
        """incr(self, size_t n = 1) -> SwigPyIterator"""
        return _slab_swig.SwigPyIterator_incr(self, n)

    def decr(self, n = 1):
        """decr(self, size_t n = 1) -> SwigPyIterator"""
        return _slab_swig.SwigPyIterator_decr(self, n)

    def distance(self, *args, **kwargs):
        """distance(self, SwigPyIterator x) -> ptrdiff_t"""
        return _slab_swig.SwigPyIterator_distance(self, *args, **kwargs)

    def equal(self, *args, **kwargs):
        """equal(self, SwigPyIterator x) -> bool"""
        return _slab_swig.SwigPyIterator_equal(self, *args, **kwargs)

    def copy(self):
        """copy(self) -> SwigPyIterator"""
        return _slab_swig.SwigPyIterator_copy(self)

    def next(self):
        """next(self) -> PyObject"""
        return _slab_swig.SwigPyIterator_next(self)

    def __next__(self):
        """__next__(self) -> PyObject"""
        return _slab_swig.SwigPyIterator___next__(self)

    def previous(self):
        """previous(self) -> PyObject"""
        return _slab_swig.SwigPyIterator_previous(self)

    def advance(self, *args, **kwargs):
        """advance(self, ptrdiff_t n) -> SwigPyIterator"""
        return _slab_swig.SwigPyIterator_advance(self, *args, **kwargs)

    def __eq__(self, *args, **kwargs):
        """__eq__(self, SwigPyIterator x) -> bool"""
        return _slab_swig.SwigPyIterator___eq__(self, *args, **kwargs)

    def __ne__(self, *args, **kwargs):
        """__ne__(self, SwigPyIterator x) -> bool"""
        return _slab_swig.SwigPyIterator___ne__(self, *args, **kwargs)

    def __iadd__(self, *args, **kwargs):
        """__iadd__(self, ptrdiff_t n) -> SwigPyIterator"""
        return _slab_swig.SwigPyIterator___iadd__(self, *args, **kwargs)

    def __isub__(self, *args, **kwargs):
        """__isub__(self, ptrdiff_t n) -> SwigPyIterator"""
        return _slab_swig.SwigPyIterator___isub__(self, *args, **kwargs)

    def __add__(self, *args, **kwargs):
        """__add__(self, ptrdiff_t n) -> SwigPyIterator"""
        return _slab_swig.SwigPyIterator___add__(self, *args, **kwargs)

    def __sub__(self, *args):
        """
        __sub__(self, ptrdiff_t n) -> SwigPyIterator
        __sub__(self, SwigPyIterator x) -> ptrdiff_t
        """
        return _slab_swig.SwigPyIterator___sub__(self, *args)

    def __iter__(self): return self
SwigPyIterator_swigregister = _slab_swig.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

sizeof_char = _slab_swig.sizeof_char
sizeof_short = _slab_swig.sizeof_short
sizeof_int = _slab_swig.sizeof_int
sizeof_float = _slab_swig.sizeof_float
sizeof_double = _slab_swig.sizeof_double
sizeof_gr_complex = _slab_swig.sizeof_gr_complex
class slab_sbhs_scilab_sptr(object):
    """Proxy of C++ boost::shared_ptr<(slab_sbhs_scilab)> class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> slab_sbhs_scilab_sptr
        __init__(self,  p) -> slab_sbhs_scilab_sptr
        """
        this = _slab_swig.new_slab_sbhs_scilab_sptr(*args)
        try: self.this.append(this)
        except: self.this = this
    def __deref__(self):
        """__deref__(self)"""
        return _slab_swig.slab_sbhs_scilab_sptr___deref__(self)

    __swig_destroy__ = _slab_swig.delete_slab_sbhs_scilab_sptr
    __del__ = lambda self : None;
    d_fan_speed = _swig_property(_slab_swig.slab_sbhs_scilab_sptr_d_fan_speed_get, _slab_swig.slab_sbhs_scilab_sptr_d_fan_speed_set)
    d_heater_temperature = _swig_property(_slab_swig.slab_sbhs_scilab_sptr_d_heater_temperature_get, _slab_swig.slab_sbhs_scilab_sptr_d_heater_temperature_set)
    def get_scilab(self, *args, **kwargs):
        """get_scilab(self, char var) -> float"""
        return _slab_swig.slab_sbhs_scilab_sptr_get_scilab(self, *args, **kwargs)

    def python_sleep(self):
        """python_sleep(self)"""
        return _slab_swig.slab_sbhs_scilab_sptr_python_sleep(self)

    def create_file(self):
        """create_file(self)"""
        return _slab_swig.slab_sbhs_scilab_sptr_create_file(self)

    def set_fan_speed(self, *args, **kwargs):
        """set_fan_speed(self, int fan_speed)"""
        return _slab_swig.slab_sbhs_scilab_sptr_set_fan_speed(self, *args, **kwargs)

    def set_heater_temperature(self, *args, **kwargs):
        """set_heater_temperature(self, int heater_temperature)"""
        return _slab_swig.slab_sbhs_scilab_sptr_set_heater_temperature(self, *args, **kwargs)

    def general_work(self, *args, **kwargs):
        """
        general_work(self, int noutput_items, gr_vector_int ninput_items, gr_vector_const_void_star input_items, 
            gr_vector_void_star output_items) -> int
        """
        return _slab_swig.slab_sbhs_scilab_sptr_general_work(self, *args, **kwargs)

    def history(self):
        """history(self) -> unsigned int"""
        return _slab_swig.slab_sbhs_scilab_sptr_history(self)

    def output_multiple(self):
        """output_multiple(self) -> int"""
        return _slab_swig.slab_sbhs_scilab_sptr_output_multiple(self)

    def relative_rate(self):
        """relative_rate(self) -> double"""
        return _slab_swig.slab_sbhs_scilab_sptr_relative_rate(self)

    def start(self):
        """start(self) -> bool"""
        return _slab_swig.slab_sbhs_scilab_sptr_start(self)

    def stop(self):
        """stop(self) -> bool"""
        return _slab_swig.slab_sbhs_scilab_sptr_stop(self)

    def detail(self):
        """detail(self) -> gr_block_detail_sptr"""
        return _slab_swig.slab_sbhs_scilab_sptr_detail(self)

    def set_detail(self, *args, **kwargs):
        """set_detail(self, gr_block_detail_sptr detail)"""
        return _slab_swig.slab_sbhs_scilab_sptr_set_detail(self, *args, **kwargs)

    def name(self):
        """name(self) -> string"""
        return _slab_swig.slab_sbhs_scilab_sptr_name(self)

    def input_signature(self):
        """input_signature(self) -> gr_io_signature_sptr"""
        return _slab_swig.slab_sbhs_scilab_sptr_input_signature(self)

    def output_signature(self):
        """output_signature(self) -> gr_io_signature_sptr"""
        return _slab_swig.slab_sbhs_scilab_sptr_output_signature(self)

    def unique_id(self):
        """unique_id(self) -> long"""
        return _slab_swig.slab_sbhs_scilab_sptr_unique_id(self)

    def basic_block(self):
        """basic_block(self) -> gr_basic_block_sptr"""
        return _slab_swig.slab_sbhs_scilab_sptr_basic_block(self)

    def check_topology(self, *args, **kwargs):
        """check_topology(self, int ninputs, int noutputs) -> bool"""
        return _slab_swig.slab_sbhs_scilab_sptr_check_topology(self, *args, **kwargs)

slab_sbhs_scilab_sptr_swigregister = _slab_swig.slab_sbhs_scilab_sptr_swigregister
slab_sbhs_scilab_sptr_swigregister(slab_sbhs_scilab_sptr)

slab_sbhs_scilab_sptr.block = lambda self: slab_sbhs_scilab_block (self)
slab_sbhs_scilab_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id ())


def sbhs_scilab(*args, **kwargs):
  """sbhs_scilab(char filename, int fan_speed, int heater_temperature) -> slab_sbhs_scilab_sptr"""
  return _slab_swig.sbhs_scilab(*args, **kwargs)


